[project]
name = "fastmcp-agents-library-mcp"
version = "0.5.1"
description = "MCP Library for FastMCP Agents"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp-agents-core[auto]",
]
[tool.uv.sources]
fastmcp-agents-core = { path = "../../../fastmcp-agents-core", editable = true }

[dependency-groups]
dev = [
    "ruff>=0.12.4",
]


[tool.ruff]
extend="../../../pyproject.toml"

[tool.pyright]
extends = "../../../pyproject.toml"