name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  list-projects:
    name: List Projects
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}
      project-names: ${{ steps.set-matrix.outputs.project-names }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          # Find all pyproject.toml files and extract project names
          echo "projects=$(find . -name "pyproject.toml" -not -path "*/.venv/*" -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          echo "project-names=$(find . -name "pyproject.toml" -not -path "*/.venv/*" -exec sh -c 'echo "{}" | xargs grep -h "^name = " | sed "s/name = //g" | sed "s/\"//g"' \; | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  test:
    name: Run Tests - ${{ matrix.project-name }}
    runs-on: ubuntu-latest
    needs: [list-projects]
    permissions:
      id-token: write
    strategy: 
      fail-fast: false 
      matrix: 
        pyproject: ${{fromJson(needs.list-projects.outputs.projects)}}
        project-name: ${{fromJson(needs.list-projects.outputs.project-names)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install uv"
        uses: astral-sh/setup-uv@v3

      - name: Sync
        run: uv sync --dev --all-groups --all-packages
        working-directory: ${{ matrix.pyproject }}

      - name: Build
        run: uv build
        working-directory: ${{ matrix.pyproject }}

      - name: Test
        run: uv run pytest -m "not skip_on_ci" -v tests/
        working-directory: ${{ matrix.pyproject }}
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MODEL: ${{ vars.MODEL }}
          MODEL_PROVIDER: gemini
