name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  list-projects:
    name: List Projects
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "$(ls **/pyproject.toml)" >> $GITHUB_OUTPUT

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [list-projects]
    permissions:
      id-token: write
    strategy: 
      fail-fast: true 
      matrix: 
        pyproject: ${{needs.list-projects.outputs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install uv"
        uses: astral-sh/setup-uv@v3

      - name: Build
        run: uv build
        working-directory: ${{ matrix.pyproject }}

      - name: Test
        run: uv run pytest -v tests/
        working-directory: ${{ matrix.pyproject }}
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MODEL: gemini-2.5-flash
          MODEL_PROVIDER: gemini
