name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  list-projects:
    name: List Projects
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          .github/scripts/list-projects.sh

  test:
    name: ${{ matrix.project-name }} - Tests
    runs-on: ubuntu-latest
    needs: [list-projects]
    permissions:
      id-token: write
    strategy: 
      fail-fast: false 
      matrix: 
        include: ${{fromJson(needs.list-projects.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install uv"
        uses: astral-sh/setup-uv@v3

      - name: Sync
        run: uv sync --dev --all-groups --all-packages
        working-directory: ${{ matrix.pyproject }}

      - name: Build
        run: uv build
        working-directory: ${{ matrix.pyproject }}

      - name: Ruff Format
        run: uv run ruff format --check .
        working-directory: ${{ matrix.pyproject }}

      - name: Ruff Check
        run: uv run ruff check .
        working-directory: ${{ matrix.pyproject }}

      - name: Type Check
        run: uv run basedpyright .
        working-directory: ${{ matrix.pyproject }}

      - name: Test
        run: uv run pytest -m "not skip_on_ci" -v tests/
        working-directory: ${{ matrix.pyproject }}
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODEL: ${{ vars.MODEL }}
          MODEL_PROVIDER: gemini
